
language: python

python:
  - "3.6"
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$(pwd)/agent
    - SN_AGENT_ID=b545478a-971a-48ec-bc56-4b9b7176799c
    - SN_SERVICE_ADAPTER_CONFIG_FILE=agent/service_adapter_config_example.yml

install:
  - pip install -r agent/requirements.txt

script:
  - py.test --verbose --cov-config agent/.coveragerc --cov=sn_agent agent/tests

after_success:
  - coveralls
